server:
  port: 9001
  error:
    includeStackTrace: never
#  ribbon:
#    ReadTimeout: 60000
#    ConnectTimeout: 20000
#    eureka:
#      enabled: false
#    ServerListRefreshInterval: 1000

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: '*'
    routes:
      enabled: true
    filters:
      enabled: true

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    user-service:
      path: /**
      serviceId: user-service

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  restclient:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true