server:
  port: 9001
  error:
    includeStackTrace: never

eureka:
#  instance:
#    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

spring:
  application:
    name: 'api-gateway'
  cloud:
    gateway:
      discovery.locator:
        enabled: true
#        lower_case_service_id: true
        lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
#          filters:
#            - PrefixPath=/aa
#          filters:
#            - name: Retry
#              args:
#                retries: 2
#                series:
#                  - SERVER_ERROR
#                statuses:
#                  - OK
#                methods:
#                  - GET
#                  - POST
#                exceptions:
#                  - java.io.IOException

#        - id: userService2
#          uri: http://localhost:9003
#          predicates:
#            - Path=/userService/**
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
#        include: beans, health, httptrace, info, routes

#logging:
#  level:
#    reactor:
#      netty: DEBUG
#    org:
#      springframework:
#        cloud:
#          gateway: DEBUG


#user-service:
#  ribbon:
#    listOfServers: http://localhost:9002,http://localhost:9003