server:
  port: 9001
  error:
    includeStackTrace: never

eureka:
#  instance:
#    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

spring:
  application:
    name: 'spring cloud'
  cloud:
    gateway:
      routes:
        - id: userService
          uri: lb://user-service
          predicates:
            - Path=/**
#          filters:
#            - name: Retry
#              args:
#                retries: 2
#                series:
#                  - SERVER_ERROR
#                statuses:
#                  - OK
#                methods:
#                  - GET
#                  - POST
#                exceptions:
#                  - java.io.IOException

#        - id: userService2
#          uri: http://localhost:9003
#          predicates:
#            - Path=/userService/**


#user-service:
#  ribbon:
#    listOfServers: http://localhost:9002,http://localhost:9003