server:
  port: 9003
  error:
    includeStackTrace: never

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

spring:
  application:
    name: auth-ws
#  datasource:
#    jdbcUrl: jdbc:mysql://localhost:3306/auth_service
#    username: auth_service
#    password: '@Auth123511'
  jpa:
    hibernate:
      ddlAuto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

#hibernate:
#  enable_lazy_load_no_trans: true

## Security
secret:
  token: secret.token

## gmail
gmail:
  smtp_host: smtp.gmail.com
  smtp_port: 587
  smtp_username: tianhui3010@gmail.com
  smtp_password: gdzdlsmghxsttadm
  smtp_sender: tianhui3010@gmail.com
#  smtp_properties:
#    mail:
#      smtp:
#        auth: true
#        starttls:
#          enable: true

logging:
  level:
    com.sean.auth.apicomm.user_ws.UserServiceClient: DEBUG

feign:
  client:
    config:
      default:
        errorDecoder: com.sean.auth.apicomm.FeignErrorDecoder
        loggerLevel: BASIC
  circuitbreaker:
    enabled: true