server:
  port: 9000

spring:
  application:
    name: discovery

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
#  server:
#    enableSelfPreservation: false
